const titleEl = document.querySelector(".title");
const memeEl = document.querySelector(".meme");
const authorEl = document.querySelector(".author");
const genMemeBtnEl = document.querySelector(".generateMemeBtn");

async function generateMeme(){
    const response = await fetch("https://meme-api.com/gimme/wholesomememes");
    const data = await response.json();
    titleEl.innerHTML = data.title;
    memeEl.setAttribute("src",data.url);
    authorEl.innerHTML = `meme generated by ${data.author}`;
    console.log(data);
}

genMemeBtnEl.addEventListener("click",generateMeme);

generateMeme();